/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progetto.ds3;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author lbrac
 */
public class PlayForm extends javax.swing.JFrame {
    Gestore g;
    StartGameForm gf;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PlayForm.class.getName());

    /**
     * Creates new form PlayForm
     */
    public PlayForm() {
        initComponents();
        
        immagine(lbl_cavaliere, "Cavaliere.png");
        immagine(lbl_mago, "Mago.png");
        immagine(lbl_vichingo, "Vichingo.png");
        
        Musica.riproduci("musica.wav");
        
        //Finestra grandezza fissa e non modificabile visibile al centro dello schermo
        this.setSize(610, 375);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        this.getContentPane().setBackground(new java.awt.Color(15, 15, 15));
        
        java.awt.Color dsSfondo = new java.awt.Color(25, 25, 25);
        java.awt.Color dsTesto = new java.awt.Color(180, 180, 160);
        
        jTextArea1.setBackground(dsSfondo);
        jTextArea1.setForeground(dsTesto);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(dsTesto, 1));
        txt_info.setBorder(null);
        
        g = new Gestore();
        
        txt_info.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cavaliere = new javax.swing.JButton();
        btn_mago = new javax.swing.JButton();
        btn_vichingo = new javax.swing.JButton();
        btn_info = new javax.swing.JButton();
        txt_info = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl_cavaliere = new javax.swing.JLabel();
        lbl_mago = new javax.swing.JLabel();
        lbl_vichingo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cavaliere.setText("Cavaliere");
        btn_cavaliere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cavaliereActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cavaliere, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btn_mago.setText("Mago");
        btn_mago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_magoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 80, -1));

        btn_vichingo.setText("Vichingo");
        btn_vichingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vichingoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_vichingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        btn_info.setText("Informazioni");
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Benvenuto nel gioco di Dark Souls 3\nQuesta è una piccola guida per la soppravivenza:\n\nAd ogni round si genera un evento casuale\nPuoi trovare un oggetto che finisce nel tuo inventario\nPuoi perdere un oggetto dal tuo inventario\nSe perdi un oggetto ma l'inventario è vuoto perdi punti vita\nPuò apparire un boss da sconfiggere in combattimento\nSe la vita è uguale o minore di 0 la partita finisce\nSe l'energia rimane negativa per troppo tempo la partita finisce\nSi può usare una sola volta per partita l'abilità per saltare un combattimento\nSi può salvare lo stato della partita per riprenderla in seguito");
        txt_info.setViewportView(jTextArea1);

        getContentPane().add(txt_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 220));
        getContentPane().add(lbl_cavaliere, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 130));
        getContentPane().add(lbl_mago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 70, 130));
        getContentPane().add(lbl_vichingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 70, 130));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(3);
        jTextArea2.setTabSize(1);
        jTextArea2.setText("Vita 100\nEnergia 5\nDanni 20");
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, 70));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(3);
        jTextArea3.setText("Vita 80\nEnergia 7\nDanni 15");
        jScrollPane2.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 80, 70));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(3);
        jTextArea4.setText("Vita 90\nEnergia 6\nDanni 25");
        jScrollPane3.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 80, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
        if(txt_info.isVisible()){
            txt_info.setVisible(false);
        }
        
        else{
            txt_info.setVisible(true);
        }
    }//GEN-LAST:event_btn_infoActionPerformed

    private void btn_cavaliereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cavaliereActionPerformed
        g.init();
        g.addPersonaggio("Cavaliere");
        gf = new StartGameForm(g, "Cavaliere.png");
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cavaliereActionPerformed

    private void btn_magoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_magoActionPerformed
        g.init();
        g.addPersonaggio("Mago");
        gf = new StartGameForm(g, "Mago.png");
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_magoActionPerformed

    private void btn_vichingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vichingoActionPerformed
        g.init();
        g.addPersonaggio("Vichingo");
        gf = new StartGameForm(g, "Vichingo.png");
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_vichingoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PlayForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cavaliere;
    private javax.swing.JButton btn_info;
    private javax.swing.JButton btn_mago;
    private javax.swing.JButton btn_vichingo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lbl_cavaliere;
    private javax.swing.JLabel lbl_mago;
    private javax.swing.JLabel lbl_vichingo;
    private javax.swing.JScrollPane txt_info;
    // End of variables declaration//GEN-END:variables

    public void immagine(javax.swing.JLabel label, String nomeFile){
        try {

        String percorso = "Documenti/Immagini/" + nomeFile;
        

        ImageIcon iconaOriginale = new ImageIcon(percorso);
        Image img = iconaOriginale.getImage();

        Image nuovaImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        

        label.setIcon(new ImageIcon(nuovaImg));
        
        } 
        
        catch (Exception e) {
            System.out.println("Errore nel caricamento dell'immagine: " + e.getMessage());
        }
    }
}
