/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progetto.ds3;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author lbrac
 */
public class StartGameForm extends javax.swing.JFrame {
    Gestore g;
    String nome;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StartGameForm.class.getName());

    /**
     * Creates new form StartGameForm
     * @param gestore
     * @param nome
     */
    public StartGameForm(Gestore gestore, String nome) {
        initComponents();
 
        this.setSize(650, 400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        this.getContentPane().setBackground(new java.awt.Color(15, 15, 15));
        java.awt.Color dsSfondo = new java.awt.Color(25, 25, 25);
        java.awt.Color dsTesto = new java.awt.Color(180, 180, 160);
        
        txt_storia.setBackground(dsSfondo);
        txt_storia.setForeground(dsTesto);
        txt_storia.setCaretColor(java.awt.Color.WHITE);

        txt_status.setBackground(dsSfondo);
        txt_status.setForeground(dsTesto);

        java.awt.Font dsFont = new java.awt.Font("Serif", java.awt.Font.PLAIN, 14);
        txt_storia.setFont(dsFont);
        txt_status.setFont(dsFont);
        
        this.g = gestore;  
        this.nome = nome;
        
        btn_round.setVisible(false);
        btn_attacca.setVisible(false);
        btn_abilita.setVisible(false);
        btn_oggetto.setVisible(false);
        btn_salta.setVisible(false);
        btn_ser.setVisible(false);
        btn_csv.setVisible(false);
        
        lbl_round.setVisible(false);
        
        txt_storia1.setVisible(false);
        txt_storia.setVisible(false);
        txt_status1.setVisible(false);
        txt_status.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_inizio = new javax.swing.JButton();
        txt_status1 = new javax.swing.JScrollPane();
        txt_status = new javax.swing.JTextArea();
        btn_round = new javax.swing.JButton();
        lbl_round = new javax.swing.JLabel();
        btn_attacca = new javax.swing.JButton();
        btn_abilita = new javax.swing.JButton();
        btn_oggetto = new javax.swing.JButton();
        txt_storia1 = new javax.swing.JScrollPane();
        txt_storia = new javax.swing.JTextArea();
        btn_salta = new javax.swing.JButton();
        btn_csv = new javax.swing.JButton();
        btn_ser = new javax.swing.JButton();
        lbl_foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inizio.setText("Inizio");
        btn_inizio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inizioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_inizio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        txt_status.setEditable(false);
        txt_status.setColumns(20);
        txt_status.setRows(5);
        txt_status.setFocusable(false);
        txt_status1.setViewportView(txt_status);

        getContentPane().add(txt_status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        btn_round.setText("Round successivo");
        btn_round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roundActionPerformed(evt);
            }
        });
        getContentPane().add(btn_round, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbl_round.setText("Round: 0");
        getContentPane().add(lbl_round, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_attacca.setText("Attacca");
        btn_attacca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attaccaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_attacca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btn_abilita.setText("Abilita");
        btn_abilita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abilitaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_abilita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        btn_oggetto.setText("oggetto");
        btn_oggetto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oggettoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_oggetto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        txt_storia.setColumns(20);
        txt_storia.setRows(5);
        txt_storia1.setViewportView(txt_storia);

        getContentPane().add(txt_storia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 240, 180));

        btn_salta.setText("Salva");
        btn_salta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saltaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        btn_csv.setText("CSV");
        btn_csv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_csvActionPerformed(evt);
            }
        });
        getContentPane().add(btn_csv, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        btn_ser.setText("SER");
        btn_ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));
        getContentPane().add(lbl_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inizioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inizioActionPerformed
        Personaggio p = g.getPersonaggio().get(0);
        
        String statistiche ="NOME: " + p.getNome() + "\n"
                       + "VITA: " + p.getVita() + "\n"
                       + "DANNI: " + p.getDanni() + "\n"
                       + "ENERGIA: " + p.getEnergia() + "\n"
                       + "PUNTI: " + p.getPunti();
        
        btn_round.setVisible(true);
        btn_attacca.setVisible(true);
        btn_abilita.setVisible(true);
        btn_oggetto.setVisible(true);
        
        lbl_round.setVisible(true);
        
        txt_storia1.setVisible(true);
        txt_storia.setVisible(true);
        txt_status1.setVisible(true);
        txt_status.setVisible(true);
        txt_status.setText(statistiche);
        btn_inizio.setVisible(false);
        
        btn_salta.setVisible(true);
        btn_ser.setVisible(true);
        btn_csv.setVisible(true);
        
        immagine(lbl_foto, nome);
    }//GEN-LAST:event_btn_inizioActionPerformed

    private void btn_abilitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abilitaActionPerformed
        String risultato = g.usareAbilita();
        txt_storia.append(risultato + "\n");
        
        if (risultato.equals("Abilita usata, salti il combattimento")) {
            Personaggio p = g.getPersonaggio().get(0);
            String statistiche = "NOME: " + p.getNome() + "\n"
                               + "VITA: " + p.getVita() + "\n"
                               + "DANNI: " + p.getDanni() + "\n"
                               + "ENERGIA: " + p.getEnergia() + "\n"
                               + "PUNTI: " + p.getPunti();
            txt_status.setText(statistiche);
            
            btn_round.setEnabled(true);
            btn_attacca.setEnabled(false);
            btn_abilita.setEnabled(false);
        }
    }//GEN-LAST:event_btn_abilitaActionPerformed

    private void btn_roundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roundActionPerformed
        String evento = g.iniziaGioco();
        lbl_round.setText("Round: " + g.getRound());
        
        if(evento.equals("VITTORIA")){
            Vittoria v = new Vittoria();
            v.setVisible (true);
            this.dispose();
        }
        
        else{
            Personaggio p = g.getPersonaggio().get(0);
            String statistiche = "NOME: " + p.getNome() + "\n"
                       + "VITA: " + p.getVita() + "\n"
                       + "DANNI: " + p.getDanni() + "\n"
                       + "ENERGIA: " + p.getEnergia() + "\n"
                       + "PUNTI: " + p.getPunti();
            txt_status.setText(statistiche);
            
            if(p.getVita() <= 0){
                Esito e = new Esito();
                e.setVisible(true);
                this.dispose();
                return;
            }
            
            if(evento.equals("Boss")){
                txt_storia.append("--- ROUND " + g.getRound() + " ---\n");
                txt_storia.append("ATTENZIONE: Appare " + g.getNomeBoss() + "!\n");
                txt_storia.setEnabled(false);
                btn_round.setEnabled(false);
                btn_attacca.setEnabled(true);
                btn_abilita.setEnabled(true);
            }
            
            else{
                txt_storia.append("---- ROUND " + g.getRound() + "----\n");
                txt_storia.append("Evento: " + evento + "\n" );
                btn_attacca.setEnabled(false);
                btn_abilita.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btn_roundActionPerformed

    private void btn_attaccaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attaccaActionPerformed
        String logAttacco = g.combatti(0);
        txt_storia.append(logAttacco);
        
        if (!g.getPersonaggio().isEmpty()) {
            Personaggio p = g.getPersonaggio().get(0);
            String statistiche = "NOME: " + p.getNome() + "\n"
                               + "VITA: " + p.getVita() + "\n"
                               + "DANNI: " + p.getDanni() + "\n"
                               + "ENERGIA: " + p.getEnergia() + "\n"
                               + "PUNTI: " + p.getPunti();
            txt_status.setText(statistiche);
        
            if (g.getNomeBoss().equals("No boss")) {
                btn_attacca.setEnabled(false);
                btn_abilita.setEnabled(false);
                btn_round.setEnabled(true);
                txt_storia.append("Vittoria! La strada è libera.\n");
            }
            
                if (p.getVita() <= 0) {
                Esito e = new Esito();
                e.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_attaccaActionPerformed

    private void btn_oggettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oggettoActionPerformed
        String messaggio = g.usaOggetto();
        txt_storia.append("Usato: " + messaggio + "\n");
        
        if (!g.getPersonaggio().isEmpty()) {
            Personaggio p = g.getPersonaggio().get(0);
            String statistiche = "NOME: " + p.getNome() + "\n"
                               + "VITA: " + p.getVita() + "\n"
                               + "DANNI: " + p.getDanni() + "\n"
                               + "ENERGIA: " + p.getEnergia() + "\n"
                               + "PUNTI: " + p.getPunti();
            txt_status.setText(statistiche);
        }
    }//GEN-LAST:event_btn_oggettoActionPerformed

    private void btn_saltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saltaActionPerformed
        Personaggio p = g.getPersonaggio().get(0);
        Salvataggio.salvaSer(p);
        Salvataggio.salvaCSV(p, g.getRound());
    }//GEN-LAST:event_btn_saltaActionPerformed

    private void btn_csvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_csvActionPerformed
        Personaggio p = Salvataggio.caricaCSV();
        
        if(p != null){
            g.getPersonaggio().clear();
            g.getPersonaggio().add(p);
            g.setRound(p.getRound());
            
            String statistiche = "NOME: " + p.getNome() + "\n"
                               + "VITA: " + p.getVita() + "\n"
                               + "DANNI: " + p.getDanni() + "\n"
                               + "ENERGIA: " + p.getEnergia() + "\n"
                               + "PUNTI: " + p.getPunti();
            txt_status.setText(statistiche);
            
            lbl_round.setText("Round: " + g.getRound());
        }
    }//GEN-LAST:event_btn_csvActionPerformed

    private void btn_serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serActionPerformed
        Personaggio p = Salvataggio.caricaSer();
        
        if(p != null){
            g.getPersonaggio().clear();
            g.getPersonaggio().add(p);
            g.setRound(p.getRound());
            
            String statistiche = "NOME: " + p.getNome() + "\n"
                               + "VITA: " + p.getVita() + "\n"
                               + "DANNI: " + p.getDanni() + "\n"
                               + "ENERGIA: " + p.getEnergia() + "\n"
                               + "PUNTI: " + p.getPunti();
            txt_status.setText(statistiche);
            
            lbl_round.setText("Round: " + g.getRound());
        }
    }//GEN-LAST:event_btn_serActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abilita;
    private javax.swing.JButton btn_attacca;
    private javax.swing.JButton btn_csv;
    private javax.swing.JButton btn_inizio;
    private javax.swing.JButton btn_oggetto;
    private javax.swing.JButton btn_round;
    private javax.swing.JButton btn_salta;
    private javax.swing.JButton btn_ser;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_round;
    private javax.swing.JTextArea txt_status;
    private javax.swing.JScrollPane txt_status1;
    private javax.swing.JTextArea txt_storia;
    private javax.swing.JScrollPane txt_storia1;
    // End of variables declaration//GEN-END:variables

    public void immagine(javax.swing.JLabel label, String nomeFile){
        try {
            String percorso = "Documenti/Immagini/" + nomeFile;

            ImageIcon iconaOriginale = new ImageIcon(percorso);
            Image img = iconaOriginale.getImage();

            Image nuovaImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);


            label.setIcon(new ImageIcon(nuovaImg));
        
        } 
        
        catch (Exception e) {
            System.out.println("Errore nel caricamento dell'immagine: " + e.getMessage());
        }
    }
}
